Repository nk3nny/LambsDanger, pull requests merged in 2020-06, with the labels that each got.

#128 Improve Task Patrols Waypoint Statement Readabilty
  addons/wp/functions/fnc_taskPatrol.sqf
Labels: enhancement

#131 Task Artillery Register Multible Side Register Issue
  addons/wp/XEH_preInit.sqf
Labels: bugfix

#122 Fix Some Module Issues
  addons/wp/CfgVehicles.hpp
  addons/wp/functions/Modules/fnc_moduleCQB.sqf
  addons/wp/functions/Modules/fnc_moduleGarrison.sqf
  addons/wp/functions/fnc_sideHasArtillery.sqf
  addons/wp/modules.hpp
  addons/wp/zeusModules.hpp
Labels: bugfix

#123 Fixes to taskRush
  addons/wp/functions/Modules/fnc_moduleCreep.sqf
  addons/wp/functions/Modules/fnc_moduleHunt.sqf
  addons/wp/functions/Modules/fnc_moduleRush.sqf
  addons/wp/functions/fnc_findClosestTarget.sqf
  addons/wp/functions/fnc_taskCreep.sqf
  addons/wp/functions/fnc_taskRush.sqf
  addons/wp/modules.hpp
Labels: bugfix

#124 Adds enhanced taskAssault
  addons/wp/XEH_PREP.hpp
  addons/wp/functions/Modules/fnc_moduleAssault.sqf
  addons/wp/functions/Modules/fnc_moduleCQB.sqf
  addons/wp/functions/fnc_doAssaultUnitReset.sqf
  addons/wp/functions/fnc_taskAssault.sqf
  addons/wp/functions/fnc_taskReset.sqf
Labels: enhancement

#125 Adds Enhanced taskCQB
  addons/wp/functions/fnc_taskCQB.sqf
Labels: enhancement

#130 Task garrison and task camp improvements
  addons/wp/functions/Modules/fnc_moduleCamp.sqf
  addons/wp/functions/Modules/fnc_moduleGarrison.sqf
  addons/wp/functions/fnc_taskCamp.sqf
  addons/wp/functions/fnc_taskGarrison.sqf
  addons/wp/modules.hpp
  addons/wp/stringtable.xml
Labels: enhancement

#126 Hotfixes for version 2.4.3
  addons/danger/functions/fnc_findReadyUnits.sqf
  addons/danger/functions/fnc_leaderAssess.sqf
  addons/danger/functions/fnc_leaderStaticDeploy.sqf
  addons/danger/functions/fnc_shareInformation.sqf
  addons/danger/functions/fnc_vehicleAssault.sqf
  addons/danger/functions/fnc_vehicleSuppress.sqf
  addons/danger/scripts/lambs_danger.fsm
  addons/danger/settings.sqf
  addons/danger/stringtable.xml
  readme.txt
Labels: bugfix, enhancement
