Repository nk3nny/LambsDanger, pull requests merged in 2020-10, with the labels that each got.

#166 Dont mount hidden sim disabled vehicles
  addons/danger/functions/fnc_leaderStaticFind.sqf
  addons/wp/functions/fnc_taskCamp.sqf
  addons/wp/functions/fnc_taskGarrison.sqf
Labels: kind/bug fix

#165 Improve debug
  addons/danger/functions/fnc_doAssault.sqf
  addons/danger/functions/fnc_doAssaultCQB.sqf
  addons/danger/functions/fnc_doFleeing.sqf
  addons/danger/functions/fnc_doHide.sqf
  addons/danger/functions/fnc_doSuppress.sqf
  addons/danger/functions/fnc_leaderArtillery.sqf
  addons/danger/functions/fnc_shareInformation.sqf
  addons/danger/functions/fnc_tacticsAssault.sqf
  addons/danger/functions/fnc_tacticsCQB.sqf
  addons/danger/functions/fnc_tacticsContact.sqf
  addons/danger/functions/fnc_tacticsFlank.sqf
  addons/danger/functions/fnc_tacticsGarrison.sqf
  addons/danger/functions/fnc_tacticsSuppress.sqf
  addons/danger/functions/fnc_vehicleAssault.sqf
  addons/danger/functions/fnc_vehicleJink.sqf
  addons/danger/functions/fnc_vehicleSuppress.sqf
  addons/danger/scripts/lambs_danger.fsm
  addons/main/functions/debug/fnc_debugLog.sqf
  addons/main/functions/debug/fnc_dotMarker.sqf
  addons/main/functions/fnc_doCallout.sqf
  addons/main/functions/fnc_findCover.sqf
  addons/wp/functions/fnc_doArtillery.sqf
  addons/wp/functions/fnc_taskArtilleryRegister.sqf
  addons/wp/functions/fnc_taskAssault.sqf
  addons/wp/functions/fnc_taskCQB.sqf
  addons/wp/functions/fnc_taskCamp.sqf
  addons/wp/functions/fnc_taskCreep.sqf
  addons/wp/functions/fnc_taskGarrison.sqf
  addons/wp/functions/fnc_taskHunt.sqf
  addons/wp/functions/fnc_taskPatrol.sqf
  addons/wp/functions/fnc_taskRush.sqf
Labels: kind/enhancement

#167 Cleanup for 2.5.0
  addons/danger/functions/ZeusModules/fnc_moduleDisableAI.sqf
  addons/danger/functions/ZeusModules/fnc_moduleDisableGroupAI.sqf
  addons/danger/functions/ZeusModules/fnc_moduleSetRadio.sqf
  addons/danger/functions/fnc_assaultSpeed.sqf
  addons/danger/functions/fnc_brain.sqf
  addons/danger/functions/fnc_brainAssess.sqf
  addons/danger/functions/fnc_brainEngage.sqf
  addons/danger/functions/fnc_brainForced.sqf
  addons/danger/functions/fnc_brainHide.sqf
  addons/danger/functions/fnc_doCover.sqf
  addons/danger/functions/fnc_doDodge.sqf
  addons/danger/functions/fnc_doFleeing.sqf
  addons/danger/functions/fnc_doHide.sqf
  addons/danger/functions/fnc_doSuppress.sqf
  addons/danger/functions/fnc_isLeader.sqf
  addons/danger/functions/fnc_leaderStaticDeploy.sqf
  addons/danger/functions/fnc_leaderStaticPack.sqf
  addons/danger/functions/fnc_shareInformation.sqf
  addons/danger/functions/fnc_shareInformationRange.sqf
  addons/danger/functions/fnc_tactics.sqf
  addons/danger/functions/fnc_tacticsAssault.sqf
  addons/danger/functions/fnc_tacticsAssess.sqf
  addons/danger/functions/fnc_tacticsCQB.sqf
  addons/danger/functions/fnc_tacticsContact.sqf
  addons/danger/functions/fnc_tacticsFlank.sqf
  addons/danger/functions/fnc_tacticsGarrison.sqf
  addons/danger/functions/fnc_tacticsHide.sqf
  addons/danger/functions/fnc_tacticsSuppress.sqf
  addons/danger/functions/fnc_vehicle.sqf
  addons/danger/functions/fnc_vehicleAssault.sqf
  addons/danger/functions/fnc_vehicleJink.sqf
  addons/danger/functions/fnc_vehicleRotate.sqf
  addons/danger/functions/fnc_vehicleSuppress.sqf
  addons/danger/functions/script_component.hpp
  addons/danger/scripts/lambs_danger.fsm
  addons/danger/settings.sqf
  addons/main/XEH_PREP.hpp
  addons/main/XEH_postInit.sqf
  addons/main/functions/debug/fnc_debugDraw.sqf
  addons/main/functions/fnc_doSmoke.sqf
  addons/main/functions/fnc_findCover.sqf
  addons/main/functions/fnc_findNearbyFriendlies.sqf
  addons/main/settings.sqf
  addons/wp/functions/fnc_taskCreep.sqf
  tools/sqf_linter_LogChecker.py
Labels: kind/bug fix, kind/enhancement, kind/optimization

#162 Polish translation for LAMBS Danger
  addons/danger/stringtable.xml
  addons/eventhandlers/stringtable.xml
  addons/main/stringtable.xml
  addons/wp/stringtable.xml
Labels: area/translations

#170 Fix Debug Controls where not deleted on Singleplayer restart
  addons/main/XEH_postInit.sqf
Labels: kind/bug fix
