Repository nk3nny/LambsDanger, pull requests merged in 2021-06, with the labels that each got.

#246 Add Range Module
  addons/range/$PBOPREFIX$
  addons/range/CfgVehicles.hpp
  addons/range/config.cpp
  addons/range/script_component.hpp
Labels: kind/feature

#247 Move WP Strings to Stringtables
  addons/wp/CfgVehicles.hpp
  addons/wp/CfgWaypoints.hpp
  addons/wp/ZEN_CfgWaypointTypes.hpp
  addons/wp/stringtable.xml
Labels: area/translations, kind/enhancement

#249 initial suppressive fire check
  addons/danger/XEH_preInitClient.sqf
  addons/danger/functions/fnc_brainEngage.sqf
  addons/danger/functions/fnc_tacticsSuppress.sqf
  addons/main/XEH_PREP.hpp
  addons/main/XEH_postInit.sqf
  addons/main/XEH_preInit.sqf
  addons/main/functions/GroupAction/fnc_doGroupFlank.sqf
  addons/main/functions/UnitAction/fnc_doAssaultMemory.sqf
  addons/main/functions/UnitAction/fnc_doSuppress.sqf
  addons/main/functions/fnc_shouldSuppressPosition.sqf
  tools/sqf_linter_LogChecker.py
Labels: kind/enhancement

#256 Fix units attacking SuppressTargets
  addons/danger/functions/fnc_brainForced.sqf
Labels: kind/bug fix

#258 Add unified doGroupHide action
  addons/danger/functions/fnc_tacticsContact.sqf
  addons/danger/functions/fnc_tacticsHide.sqf
  addons/danger/functions/fnc_tacticsHold.sqf
  addons/main/XEH_PREP.hpp
  addons/main/functions/GroupAction/fnc_doGroupHide.sqf
  addons/main/functions/UnitAction/fnc_doHide.sqf
  addons/main/functions/debug/fnc_debugDraw.sqf
Labels: kind/enhancement

#263 Use Native Hashes for Artillery System
  addons/wp/XEH_preInit.sqf
Labels: kind/enhancement

#265 move findClosestTarget to Main
  addons/main/XEH_PREP.hpp
  addons/main/functions/fnc_findClosestTarget.sqf
  addons/wp/XEH_PREP.hpp
  addons/wp/functions/fnc_taskCreep.sqf
  addons/wp/functions/fnc_taskHunt.sqf
  addons/wp/functions/fnc_taskRush.sqf
Labels: kind/enhancement

#264 Fix Issues that Artillery Guns not Getting Readded in certain cases.
  addons/wp/functions/fnc_doArtillery.sqf
Labels: kind/bug fix

#259 Improve taskCamp, taskCamp and taskGarrison waypoints with eventhandlers
  addons/main/XEH_PREP.hpp
  addons/main/functions/fnc_removeEventhandlers.sqf
  addons/wp/XEH_preInit.sqf
  addons/wp/functions/Modules/fnc_moduleGarrison.sqf
  addons/wp/functions/fnc_taskCamp.sqf
  addons/wp/functions/fnc_taskGarrison.sqf
  addons/wp/functions/fnc_taskHunt.sqf
  addons/wp/functions/fnc_taskReset.sqf
  addons/wp/modules.hpp
  addons/wp/stringtable.xml
Labels: kind/enhancement

#228 Improving doDodge running in place
  addons/main/functions/UnitAction/fnc_doDodge.sqf
Labels: kind/bug fix, kind/enhancement

#267 Fix doSelectWarhead errors
  addons/danger/functions/fnc_brainVehicle.sqf
  addons/main/functions/VehicleAction/fnc_doSelectWarhead.sqf
Labels: kind/bug fix

#269 Improve Task Hunt by using doUGL for Flares
  addons/main/functions/UnitAction/fnc_doUGL.sqf
  addons/wp/functions/Modules/fnc_moduleHunt.sqf
  addons/wp/functions/fnc_taskHunt.sqf
  addons/wp/modules.hpp
  addons/wp/script_component.hpp
  addons/wp/stringtable.xml
Labels: kind/enhancement

#271 Remove a duplicated stringtable entry
  addons/danger/settings.sqf
  addons/danger/stringtable.xml
  addons/wp/settings.sqf
Labels: area/translations, ignore changelog, kind/optimization

#270 add check if StringtableEntries are unused
  tools/stringtableChecker/stringTableChecker.js
Labels: area/tools, area/translations, kind/enhancement

#274 Fix the 3den Artillery Register Checkbox was not working
  addons/wp/Cfg3DEN.hpp
Labels: kind/bug fix

#275 Fix Zen Action for TaskPatrol calling wrong Event
  addons/wp/functions/ZEN/fnc_setPatrol.sqf
Labels: kind/bug fix
