Repository nk3nny/LambsDanger, pull requests merged in 2021-03, with the labels that each got.

#187 Fixes and improves User Interface
  addons/danger/XEH_preInitClient.sqf
Labels: kind/enhancement, status/discussion

#186 Fixes Garrisoned and Camped reinforcements
  addons/danger/functions/fnc_tacticsReinforce.sqf
  addons/danger/stringtable.xml
  addons/wp/functions/fnc_taskReset.sqf
Labels: kind/bug fix

#188 Performance and optimalization
  addons/danger/functions/fnc_brain.sqf
  addons/danger/functions/fnc_brainAssess.sqf
  addons/danger/functions/fnc_brainEngage.sqf
  addons/danger/functions/fnc_brainHide.sqf
  addons/danger/functions/fnc_brainReact.sqf
  addons/danger/functions/fnc_tacticsAssess.sqf
  addons/danger/functions/fnc_tacticsContact.sqf
  addons/main/functions/UnitAction/fnc_doAssaultCQB.sqf
  addons/main/functions/UnitAction/fnc_doDodge.sqf
  addons/main/functions/UnitAction/fnc_doFleeing.sqf
  addons/main/functions/UnitAction/fnc_doHide.sqf
Labels: kind/enhancement, kind/optimization

#192 Update for Polish translation (LAMBS 2.5.0 RC)
  addons/danger/stringtable.xml
  addons/main/stringtable.xml
  addons/wp/stringtable.xml
Labels: area/translations

#195 Fix debug draw caching issues
  addons/main/XEH_postInit.sqf
  addons/main/functions/debug/fnc_debugDraw.sqf
  addons/main/settings.sqf
Labels: kind/bug fix, kind/enhancement

#194 Remove doFire from tacticsContacts
  addons/danger/functions/fnc_tacticsContact.sqf
Labels: kind/bug fix, kind/enhancement

#198 Add Russian translation
  addons/danger/stringtable.xml
  addons/eventhandlers/stringtable.xml
  addons/main/stringtable.xml
  addons/wp/stringtable.xml
Labels: area/translations

#199 Fix Zen Context Menu Actions Conditions
  addons/danger/ZEN_CfgContext.hpp
  addons/wp/ZEN_CfgContext.hpp
Labels: kind/bug fix

#200 Unify NewLines in Stringtables
  addons/danger/stringtable.xml
  addons/main/stringtable.xml
  addons/wp/stringtable.xml
Labels: kind/enhancement
