Repository nk3nny/LambsDanger, pull requests merged in 2021-04, with the labels that each got.

#202 fix launcher select in tacticshide and add some brackets
  addons/danger/functions/fnc_tacticsHide.sqf
  addons/wp/functions/fnc_doAssaultUnitReset.sqf
  addons/wp/functions/fnc_taskCamp.sqf
  addons/wp/functions/fnc_taskRush.sqf
Labels: kind/bug fix

#206 Fix Slider Percentage Issue
  addons/danger/settings.sqf
  addons/main/settings.sqf
Labels: kind/bug fix

#203 Convert remoteExec/remoteExecCall to CBA Target Events
  addons/wp/XEH_preInit.sqf
  addons/wp/functions/Modules/fnc_moduleAssault.sqf
  addons/wp/functions/Modules/fnc_moduleCQB.sqf
  addons/wp/functions/Modules/fnc_moduleCamp.sqf
  addons/wp/functions/Modules/fnc_moduleCreep.sqf
  addons/wp/functions/Modules/fnc_moduleGarrison.sqf
  addons/wp/functions/Modules/fnc_moduleHunt.sqf
  addons/wp/functions/Modules/fnc_modulePatrol.sqf
  addons/wp/functions/Modules/fnc_moduleReset.sqf
  addons/wp/functions/Modules/fnc_moduleRush.sqf
  addons/wp/functions/ZEN/fnc_setCQB.sqf
  addons/wp/functions/ZEN/fnc_setCamp.sqf
  addons/wp/functions/ZEN/fnc_setCreep.sqf
  addons/wp/functions/ZEN/fnc_setGarrison.sqf
  addons/wp/functions/ZEN/fnc_setHunt.sqf
  addons/wp/functions/ZEN/fnc_setPatrol.sqf
  addons/wp/functions/ZEN/fnc_setReset.sqf
  addons/wp/functions/ZEN/fnc_setRush.sqf
Labels: kind/enhancement

#196 Use CompileScript when DISABLE_COMPILE_CACHE Is used
  addons/main/script_macros.hpp
Labels: kind/enhancement

#201 Add custom share information handlers
  CONTRIBUTING.md
  addons/main/XEH_PREP.hpp
  addons/main/XEH_preInit.sqf
  addons/main/functions/fnc_addShareInformationHandler.sqf
  addons/main/functions/fnc_doShareInformation.sqf
Labels: kind/enhancement

#189 Improve Tactics Contact State
  addons/danger/functions/fnc_tacticsContact.sqf
Labels: kind/bug fix, kind/enhancement

#190 Brain performance and timings
  addons/danger/XEH_PREP.hpp
  addons/danger/functions/fnc_brain.sqf
  addons/danger/functions/fnc_brainEngage.sqf
  addons/danger/functions/fnc_brainForced.sqf
  addons/danger/functions/fnc_brainReact.sqf
  addons/danger/functions/fnc_brainVehicle.sqf
  addons/danger/functions/fnc_isForced.sqf
  addons/danger/functions/fnc_isForcedExit.sqf
  addons/danger/functions/fnc_isLeader.sqf
  addons/danger/scripts/lambs_danger.fsm
  addons/main/functions/UnitAction/fnc_doDodge.sqf
  addons/main/functions/UnitAction/fnc_doHide.sqf
Labels: kind/enhancement

#191 Group and tactical enhancements
  addons/danger/functions/fnc_tacticsAssault.sqf
  addons/danger/functions/fnc_tacticsAssess.sqf
  addons/danger/functions/fnc_tacticsFlank.sqf
  addons/danger/functions/fnc_tacticsGarrison.sqf
  addons/danger/functions/fnc_tacticsReinforce.sqf
  addons/danger/functions/fnc_tacticsSuppress.sqf
  addons/main/XEH_PREP.hpp
  addons/main/functions/GroupAction/fnc_doGroupAssault.sqf
  addons/main/functions/GroupAction/fnc_doGroupFlank.sqf
  addons/main/functions/GroupAction/fnc_doGroupSuppress.sqf
  addons/main/functions/UnitAction/fnc_doAssault.sqf
  addons/main/functions/UnitAction/fnc_doSuppress.sqf
  addons/main/functions/VehicleAction/fnc_doVehicleAssault.sqf
  addons/main/functions/VehicleAction/fnc_doVehicleSuppress.sqf
  addons/main/functions/fnc_doShareInformation.sqf
  addons/main/functions/fnc_findNearbyFriendlies.sqf
  addons/main/functions/fnc_findReadyUnits.sqf
  addons/main/functions/fnc_findReadyVehicles.sqf
  addons/main/functions/fnc_getShareInformationParams.sqf
  addons/main/functions/fnc_isAlive.sqf
  addons/main/settings.sqf
Labels: kind/bug fix, kind/enhancement

#209 Improves isNight check performance by RCA3
  addons/main/functions/fnc_isNight.sqf
Labels: kind/enhancement

#210 Improve AI Artillery -- disembarking and improving doArtillery
  addons/danger/functions/fnc_brainVehicle.sqf
  addons/wp/functions/fnc_doArtillery.sqf
  addons/wp/functions/fnc_taskArtillery.sqf
Labels: kind/bug fix, kind/enhancement

#219 fix issue with taskAssault calling taskArtillery
  addons/wp/XEH_preInit.sqf
Labels: kind/bug fix

#218 Prevent Script Errors with TaskArtillery when no Artillery is defined
  addons/wp/XEH_preInit.sqf
Labels: kind/bug fix

#216 add ZEN Context Actions for Reinforcement
  addons/danger/XEH_PREP.hpp
  addons/danger/ZEN_CfgContext.hpp
  addons/danger/functions/ZEN/fnc_setReinforcement.sqf
  addons/danger/functions/ZEN/fnc_showReinforcement.sqf
  addons/danger/stringtable.xml
Labels: kind/enhancement

#215 Rename DisableGroupAI Module to Configure Group AI
  addons/danger/CfgVehicles.hpp
  addons/danger/XEH_PREP.hpp
  addons/danger/functions/ZeusModules/fnc_moduleConfigureGroupAI.sqf
  addons/danger/stringtable.xml
Labels: kind/enhancement

#217 Improve Render Positions of DebugDraw
  addons/main/functions/debug/fnc_debugDraw.sqf
Labels: kind/enhancement

#223 Fix armored vehicles suppressing useless positions
  addons/main/functions/VehicleAction/fnc_doVehicleAssault.sqf
Labels: kind/bug fix

#225 Fix brain engage suppression bug and add minor tweaks
  addons/danger/functions/fnc_brainEngage.sqf
Labels: kind/enhancement

#222 Simplified Params array in fsm
  addons/danger/scripts/lambs_danger.fsm
Labels: kind/enhancement

#226 Fix contact state errors
  addons/danger/functions/fnc_tacticsContact.sqf
Labels: kind/enhancement

#227 Remove assault stance changes
  addons/main/functions/UnitAction/fnc_doAssault.sqf
  addons/main/functions/UnitAction/fnc_doAssaultMemory.sqf
Labels: kind/enhancement

#229 add pbo prefix for formations module
  addons/formations/$PBOPREFIX$
Labels: kind/bug fix

#238 Improve Regex in stringtableChecker to include Config String macros
  tools/stringtableChecker/stringTableChecker.js
Labels: ignore changelog, kind/enhancement

#231 Fix retreat option in task assault
  addons/wp/functions/fnc_doAssaultUnitReset.sqf
  addons/wp/functions/fnc_taskAssault.sqf
Labels: kind/bug fix

#232 Fixes excessive use of AI smoke
  addons/danger/functions/fnc_tacticsAssault.sqf
  addons/danger/functions/fnc_tacticsAssess.sqf
  addons/danger/functions/fnc_tacticsFlank.sqf
Labels: kind/bug fix, kind/enhancement

#234 Prevents sharing information to player group
  addons/main/functions/fnc_doShareInformation.sqf
Labels: kind/bug fix, kind/enhancement

#233 Refines Suppression in brainEngage and tacticsAssess
  addons/danger/functions/fnc_brainEngage.sqf
  addons/danger/functions/fnc_tacticsAssess.sqf
Labels: kind/enhancement

#236 Cleanup Task Module Configs
  addons/wp/modules.hpp
Labels: kind/enhancement

#237 Add Checkbox to disable Reinforcement system for Task Waypoints
  addons/wp/functions/Modules/fnc_moduleHunt.sqf
  addons/wp/functions/Modules/fnc_modulePatrol.sqf
  addons/wp/functions/fnc_taskHunt.sqf
  addons/wp/functions/fnc_taskPatrol.sqf
  addons/wp/modules.hpp
  addons/wp/script_component.hpp
  addons/wp/stringtable.xml
Labels: kind/feature

#230 Improve and optimise debug draw
  addons/main/XEH_postInit.sqf
  addons/main/functions/debug/fnc_debugDraw.sqf
  addons/main/settings.sqf
  addons/main/stringtable.xml
Labels: kind/enhancement, kind/optimization

#235 Minor fixes to language in waypoints
  addons/wp/CfgWaypoints.hpp
Labels: kind/bug fix, kind/enhancement

#241 Update for Polish translation (LAMBS 2.5.1 RC4)
  addons/danger/stringtable.xml
  addons/main/stringtable.xml
  addons/wp/stringtable.xml
Labels: area/translations
