Repository nk3nny/LambsDanger, pull requests merged in 2021-05, with the labels that each got.

#243 Improve Suppression settings and stringtables
  addons/main/functions/UnitAction/fnc_doSuppress.sqf
  addons/main/settings.sqf
  addons/main/stringtable.xml
Labels: kind/bug fix, kind/enhancement

#244 Fixes circular flanking and prevents leaders from suppressing
  addons/danger/functions/fnc_tacticsFlank.sqf
  addons/main/functions/GroupAction/fnc_doGroupFlank.sqf
Labels: kind/bug fix, kind/enhancement

#245 Remove and Cleanup Todos
  addons/main/functions/UnitAction/fnc_doAssault.sqf
  addons/main/functions/UnitAction/fnc_doAssaultMemory.sqf
  addons/main/settings.sqf
  addons/wp/functions/Modules/fnc_moduleArtillery.sqf
  addons/wp/functions/Modules/fnc_moduleArtilleryRegister.sqf
  addons/wp/functions/Modules/fnc_moduleAssault.sqf
  addons/wp/functions/Modules/fnc_moduleCQB.sqf
  addons/wp/functions/Modules/fnc_moduleCamp.sqf
  addons/wp/functions/Modules/fnc_moduleCreep.sqf
  addons/wp/functions/Modules/fnc_moduleGarrison.sqf
  addons/wp/functions/Modules/fnc_moduleHunt.sqf
  addons/wp/functions/Modules/fnc_modulePatrol.sqf
  addons/wp/functions/Modules/fnc_moduleReset.sqf
  addons/wp/functions/Modules/fnc_moduleRush.sqf
  addons/wp/functions/Modules/fnc_moduleTarget.sqf
Labels: area/documentation

#253 Fix civilian fsm exit conditions
  addons/danger/scripts/lambs_dangerCivilian.fsm
Labels: kind/bug fix

#255 Fix assault/garrison issue with taskAssess
  addons/danger/functions/fnc_tacticsAssess.sqf
Labels: kind/enhancement
