Repository nk3nny/LambsDanger, pull requests merged in 2021-08, with the labels that each got.

#277 Polish translation - update for LAMBS 2.5.2 Dev 2
  addons/main/stringtable.xml
  addons/wp/stringtable.xml
Labels: area/translations

#276 Move min obstacle proximity to setting
  addons/main/XEH_preInit.sqf
  addons/main/settings.sqf
  addons/main/stringtable.xml
Labels: kind/enhancement, kind/feature

#257 Initial SqfCSupport
  .gitattributes
  .gitignore
  addons/danger/CfgEventHandlers.hpp
  addons/danger/stringtable.xml
  addons/eventhandlers/CfgEventHandlers.hpp
  addons/main/CfgEventHandlers.hpp
  addons/main/functions/script_component.hpp
  addons/main/script_macros.hpp
  addons/main/stringtable.xml
  addons/wp/CfgEventHandlers.hpp
  addons/wp/stringtable.xml
  hemtt.toml
  include/x/cba/addons/main/script_macros_common.hpp
  sqfc.json
  tools/sqf_linter_LogChecker.py
  tools/stringtableChecker/stringTableChecker.js
Labels: kind/enhancement
