Repository nk3nny/LambsDanger, pull requests merged in 2022-02, with the labels that each got.

#297 Added Translation IT/GER
  CONTRIBUTING.md
  addons/danger/stringtable.xml
  addons/eventhandlers/stringtable.xml
  addons/main/stringtable.xml
  addons/wp/stringtable.xml
Labels: area/translations

#301 Fix taskReset resetting anims for unconscious or mounted units
  addons/wp/functions/fnc_taskReset.sqf
Labels: kind/bug fix

#302 Fix taskCamp forcing animations on units in vehicles
  addons/wp/functions/fnc_taskCamp.sqf
Labels: kind/bug fix

#303 Improve doGroupHide and tacticsContact timings
  addons/danger/functions/fnc_tacticsContact.sqf
  addons/main/functions/GroupAction/fnc_doGroupHide.sqf
Labels: kind/enhancement

#305 Improve AI dodging evaluation
  addons/danger/functions/fnc_brain.sqf
Labels: kind/enhancement, kind/bug fix

#306 Improve assault memory and engagement routines
  addons/danger/functions/fnc_brainAssess.sqf
  addons/danger/functions/fnc_brainEngage.sqf
  addons/main/functions/UnitAction/fnc_doAssault.sqf
  addons/main/functions/UnitAction/fnc_doAssaultMemory.sqf
Labels: kind/enhancement, kind/bug fix

#307 Improve Garrison group tactics
  addons/danger/functions/fnc_tacticsGarrison.sqf
  tools/sqf_linter_LogChecker.py
Labels: kind/enhancement

#308 Improve Assault group tactics
  addons/danger/functions/fnc_tacticsAssault.sqf
  addons/main/functions/GroupAction/fnc_doGroupAssault.sqf
Labels: kind/enhancement

#309 Improved tactics assess
  addons/danger/functions/fnc_tacticsAssess.sqf
Labels: kind/enhancement, kind/bug fix
