Repository nk3nny/LambsDanger, pull requests merged in 2023-02, with the labels that each got.

#325 Upgrade Chinese translation
  addons/danger/stringtable.xml
  addons/main/stringtable.xml
  addons/wp/stringtable.xml
Labels: area/translations

#330 Prevent Sensor Data to be Requested on Remote Units when Debug Draw is enabled
  addons/main/functions/debug/fnc_debugDraw.sqf
Labels: kind/bug fix

#331 Add Error when Loading Lambs only on Clients but not on the Server
  addons/main/XEH_preInit.sqf
Labels: kind/enhancement

#332 Fix for Editorconfig-Checker error
  .github/workflows/main.yml
Labels: kind/bug fix

#329 Improve assault behaviour
  addons/danger/functions/fnc_brainAssess.sqf
  addons/danger/functions/fnc_brainEngage.sqf
  addons/danger/functions/fnc_brainForced.sqf
  addons/danger/functions/fnc_isForced.sqf
  addons/danger/functions/fnc_isForcedExit.sqf
  addons/danger/functions/fnc_tacticsAssault.sqf
  addons/danger/functions/fnc_tacticsAssess.sqf
  addons/danger/functions/fnc_tacticsAttack.sqf
  addons/danger/functions/fnc_tacticsContact.sqf
  addons/danger/functions/fnc_tacticsFlank.sqf
  addons/danger/functions/fnc_tacticsGarrison.sqf
  addons/danger/functions/fnc_tacticsHide.sqf
  addons/danger/functions/fnc_tacticsHold.sqf
  addons/danger/functions/fnc_tacticsSuppress.sqf
  addons/danger/scripts/lambs_danger.fsm
  addons/main/functions/GroupAction/fnc_doGroupAssault.sqf
  addons/main/functions/UnitAction/fnc_doAssault.sqf
  addons/main/functions/UnitAction/fnc_doAssaultMemory.sqf
Labels: kind/enhancement

#336 Fix extra space in doCallout
  addons/main/functions/fnc_doCallout.sqf
Labels: kind/bug fix
