Repository nk3nny/LambsDanger, pull requests merged in 2024-07, with the labels that each got.

#395 Improve GetLauncherUnits
  addons/danger/functions/fnc_tacticsAssess.sqf
  addons/danger/functions/fnc_tacticsHide.sqf
  addons/main/functions/UnitAction/fnc_doSmoke.sqf
  addons/main/functions/fnc_getLauncherUnits.sqf
  addons/main/script_macros.hpp
  addons/wp/functions/fnc_taskRush.sqf
Labels: kind/optimization

#397 Use file exists for do callout
  addons/main/functions/fnc_doCallout.sqf
Labels: kind/enhancement, kind/bug fix

#398 Add Deprecated to Vanilla Waypoints
  addons/wp/CfgWaypoints.hpp
  addons/wp/stringtable.xml
Labels: status/discussion

#403 Improve garrison and task patrols
  addons/wp/functions/fnc_taskCamp.sqf
  addons/wp/functions/fnc_taskGarrison.sqf
  tools/sqf_linter_LogChecker.py
Labels: kind/enhancement

#404 Update fnc_taskRush.sqf
  addons/wp/functions/fnc_taskRush.sqf
Labels: kind/enhancement
