Repository nk3nny/LambsDanger, pull requests merged in 2024-02, with the labels that each got.

#345 Improve Group and Contact Suppression
  addons/danger/functions/fnc_tacticsContact.sqf
  addons/main/functions/GroupAction/fnc_doGroupSuppress.sqf
  addons/main/functions/fnc_isIndoor.sqf
  tools/sqf_linter_LogChecker.py
Labels: kind/enhancement

#349 Improvements to vehicle Brain
  addons/danger/functions/fnc_brainVehicle.sqf
  addons/danger/functions/fnc_tacticsAssess.sqf
  addons/danger/functions/fnc_tacticsFlank.sqf
  addons/main/functions/GroupAction/fnc_doGroupFlank.sqf
  addons/main/functions/GroupAction/fnc_doGroupStaticFind.sqf
  addons/main/functions/UnitAction/fnc_doFleeing.sqf
  addons/main/functions/VehicleAction/fnc_doVehicleAssault.sqf
  addons/main/functions/VehicleAction/fnc_doVehicleRotate.sqf
Labels: kind/enhancement, kind/bug fix

#352 Improved Handling of assaulting Group Memory positions
  addons/danger/functions/fnc_brainAssess.sqf
  addons/danger/functions/fnc_brainEngage.sqf
  addons/danger/functions/fnc_tacticsAssault.sqf
  addons/danger/functions/fnc_tacticsAssess.sqf
  addons/main/functions/GroupAction/fnc_doGroupAssault.sqf
  addons/main/functions/UnitAction/fnc_doAssault.sqf
  addons/main/functions/UnitAction/fnc_doAssaultMemory.sqf
  addons/main/functions/UnitAction/fnc_doDodge.sqf
Labels: kind/enhancement

#353 Update fnc_doUGL.sqf
  addons/main/functions/UnitAction/fnc_doUGL.sqf
Labels: kind/enhancement

#354 Update fnc_doCheckBody.sqf
  addons/main/functions/UnitAction/fnc_doCheckBody.sqf
Labels: kind/enhancement

#355 Update fnc_doCallout
  addons/main/functions/fnc_doCallout.sqf
Labels: kind/enhancement

#357 Optimize door finding in findBuildings
  addons/main/functions/fnc_findBuildings.sqf
Labels: kind/optimization

#358 Improve explosionEH
  addons/eventhandlers/functions/fnc_explosionEH.sqf
Labels: kind/enhancement, kind/bug fix

#360 Improve building filtering
  addons/main/functions/fnc_findBuildings.sqf
Labels: kind/bug fix

#363 fnc_findReadyVehicles ammo check
  addons/main/functions/fnc_findReadyVehicles.sqf
Labels: kind/bug fix

#364 Fixed type declaration
  addons/main/functions/fnc_showDialog.sqf
Labels: kind/enhancement

#366 Add Caching to Muzzle Check in doSmokeShell
  addons/main/XEH_PREP.hpp
  addons/main/functions/UnitAction/fnc_doSmoke.sqf
  addons/main/functions/fnc_getCompatibleThrowMuzzle.sqf
Labels: kind/enhancement

#374 Fix issues relating to constant dismounts
  addons/danger/XEH_preInit.sqf
  addons/main/functions/UnitAction/fnc_doFleeing.sqf
  addons/main/functions/UnitAction/fnc_doHide.sqf
  addons/main/functions/fnc_doShareInformation.sqf
  addons/main/functions/fnc_getShareInformationParams.sqf
Labels: kind/bug fix

#375 Fix Let LAMBS Danger control unit stances
  addons/formations/CfgVehicles.hpp
Labels: kind/enhancement, kind/bug fix

#333 Adds better support for MLRS artillery
  addons/wp/functions/fnc_doArtillery.sqf
  addons/wp/functions/fnc_taskArtilleryRegister.sqf
  addons/wp/stringtable.xml
Labels: kind/enhancement

#359 Tweaks to core tested internally
  addons/danger/functions/fnc_brainVehicle.sqf
  addons/danger/functions/fnc_tacticsAssess.sqf
  addons/danger/functions/fnc_tacticsFlank.sqf
  addons/danger/functions/fnc_tacticsReinforce.sqf
  addons/danger/scripts/lambs_dangerCivilian.fsm
  addons/main/functions/GroupAction/fnc_doGroupAssault.sqf
  addons/main/functions/GroupAction/fnc_doGroupFlank.sqf
  addons/main/functions/UnitAction/fnc_doAssault.sqf
  addons/main/functions/UnitAction/fnc_doAssaultMemory.sqf
  addons/main/functions/UnitAction/fnc_doAssaultSpeed.sqf
Labels: kind/enhancement, kind/bug fix, status/WIP

#381 Update fnc_getCompatibleThrowMuzzle.sqf
  addons/main/functions/fnc_getCompatibleThrowMuzzle.sqf
Labels: kind/bug fix
