Repository nk3nny/LambsDanger, pull requests merged in 2024-05, with the labels that each got.

#382 Fix Inconsitent Caching of checkMagazineAiUsageFlags
  addons/main/functions/fnc_checkMagazineAiUsageFlags.sqf
Labels: kind/bug fix

#361 checkVisibility comparison fixes
  addons/main/functions/GroupAction/fnc_doGroupAssault.sqf
  addons/main/functions/UnitAction/fnc_doFleeing.sqf
Labels: kind/bug fix

#383 Fixes some instances of groups shooting into air
  addons/danger/functions/fnc_tacticsAssault.sqf
  addons/danger/functions/fnc_tacticsContact.sqf
  addons/danger/functions/fnc_tacticsFlank.sqf
  addons/danger/functions/fnc_tacticsSuppress.sqf
Labels: kind/bug fix

#385 Improves fnc_doGroupAssault
  addons/main/functions/GroupAction/fnc_doGroupAssault.sqf
Labels: kind/enhancement

#386 Update fnc_tacticsFlank.sqf
  addons/danger/functions/fnc_tacticsFlank.sqf
Labels: kind/enhancement

#387 Fixes and improves doAssaultMemory
  addons/danger/functions/fnc_brainAssess.sqf
  addons/main/functions/UnitAction/fnc_doAssaultMemory.sqf
Labels: kind/enhancement, kind/bug fix

#388 Improve vehicle maneuverability and defenses
  addons/danger/functions/fnc_brainVehicle.sqf
  addons/danger/functions/fnc_tacticsAssault.sqf
  addons/main/functions/GroupAction/fnc_doGroupFlank.sqf
  addons/main/functions/VehicleAction/fnc_doVehicleJink.sqf
  tools/sqf_linter_LogChecker.py
Labels: kind/enhancement

#389 Add features to fnc_tacticsReinforce.sqf
  addons/danger/functions/fnc_tacticsReinforce.sqf
Labels: kind/enhancement, status/WIP
