Repository nk3nny/LambsDanger, pull requests merged in 2025-01, with the labels that each got.

#412 Utilize throwables command
  addons/main/functions/UnitAction/fnc_doSmoke.sqf
Labels: kind/enhancement

#417 Fix Macro in Version Mismatch Message
  addons/main/XEH_preInit.sqf
Labels: kind/bug fix

#418 Eventhandlers - Add Delay to AI Explosion Reaction
  addons/eventhandlers/CfgEventHandlers.hpp
  addons/eventhandlers/XEH_PREP.hpp
  addons/eventhandlers/functions/fnc_delayExplosionEH.sqf
Labels: kind/enhancement

#420 Fix group assaults
  addons/danger/functions/fnc_tacticsAssault.sqf
  addons/main/functions/GroupAction/fnc_doGroupAssault.sqf
Labels: kind/enhancement, kind/bug fix

#421 Improvements to brainEngage
  addons/danger/functions/fnc_brainEngage.sqf
  addons/main/functions/UnitAction/fnc_doAssault.sqf
  addons/main/functions/UnitAction/fnc_doAssaultMemory.sqf
Labels: kind/enhancement, kind/bug fix

#422 Improve Dodging and reactions
  addons/danger/functions/fnc_brainReact.sqf
  addons/main/functions/UnitAction/fnc_doCover.sqf
  addons/main/functions/UnitAction/fnc_doDodge.sqf
Labels: kind/enhancement

#423 Fix tactics Contact Triggering inside
  addons/danger/functions/fnc_tacticsContact.sqf
Labels: kind/enhancement

#425 fixes from experimental hemtt linter with most aggressive linter settings
  addons/danger/functions/fnc_fsmAllowAnimation.sqf
  addons/danger/functions/fnc_tacticsContact.sqf
  addons/danger/functions/fnc_tacticsSuppress.sqf
  addons/danger/settings.inc.sqf
  addons/main/functions/GroupAction/fnc_doGroupStaticPack.sqf
  addons/main/functions/GroupAction/fnc_doGroupSuppress.sqf
  addons/main/functions/UnitAction/fnc_doDodge.sqf
  addons/main/functions/VehicleAction/fnc_doVehicleSuppress.sqf
  addons/main/functions/fnc_doShareInformation.sqf
  addons/main/functions/fnc_showDialog.sqf
  addons/wp/functions/Modules/fnc_moduleCreep.sqf
  addons/wp/functions/Modules/fnc_moduleHunt.sqf
  addons/wp/functions/Modules/fnc_moduleRush.sqf
  addons/wp/functions/fnc_taskArtilleryRegister.sqf
Labels: kind/enhancement

#426 Update fnc_debugDraw.sqf
  addons/main/functions/debug/fnc_debugDraw.sqf
Labels: kind/enhancement

#428 Adds teleport option to taskPatrol
  addons/wp/functions/Modules/fnc_moduleCamp.sqf
  addons/wp/functions/Modules/fnc_moduleGarrison.sqf
  addons/wp/functions/Modules/fnc_modulePatrol.sqf
  addons/wp/functions/fnc_taskCamp.sqf
  addons/wp/functions/fnc_taskGarrison.sqf
  addons/wp/functions/fnc_taskPatrol.sqf
  addons/wp/modules.hpp
  addons/wp/script_component.hpp
  addons/wp/stringtable.xml
Labels: kind/feature

#429 Add Defense Module
  addons/wp/XEH_PREP.hpp
  addons/wp/XEH_preInit.sqf
  addons/wp/config.cpp
  addons/wp/functions/Modules/fnc_moduleDefend.sqf
  addons/wp/functions/ZEN/fnc_setDefend.sqf
  addons/wp/functions/fnc_taskDefend.sqf
  addons/wp/modules.hpp
  addons/wp/script_component.hpp
  addons/wp/stringtable.xml
  addons/wp/zeusModules.hpp
  tools/sqf_linter_LogChecker.py
Labels: kind/enhancement
